version: '3.8'

#CASSANDRA_USER default cassandra
#CASSANDRA_PASSWORD default cassandra

services:
  cassandra_db:
    image: cassandra:4
    restart: always
    container_name: 'cassandra_db'
    ports:
      - '9042:9042'
    environment:
      CASSANDRA_CLUSTER_NAME: "chatapp"