version: '3.8'

#CASSANDRA_USER default cassandra
#CASSANDRA_PASSWORD default cassandra

services:
  mysql_db:
    image: mysql:8.0
    restart: always
    container_name: 'mysql_db'
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "chatapp"
      MYSQL_USER: "chatapp"
      MYSQL_PASSWORD: "Ch@t@pp"
      MYSQL_ROOT_PASSWORD: "Ch@t@pp"
